# F3V3R DR34M CONFIGURATION - ULTIMATE KEYGEN STYLE
# ================================================

# 🔥 OLLAMA CONFIGURATION 🔥
ollama:
  host: 0.0.0.0
  port: 11434
  default_model: llama3.2
  models:
    - llama3.2
    - mistral
    - codellama

# 🚀 STABLE DIFFUSION CONFIGURATION 🚀
stable_diffusion:
  host: 0.0.0.0
  port: 7860
  models:
    - stable-diffusion-xl
    - stable-diffusion-v1.5

# 💻 RUNTIME SETTINGS 💻
runtime:
  cross_platform_support: true
  debug_mode: false
  logging_level: INFO
